name: Expo iOS Prebuild

on:
  workflow_dispatch:

jobs:
  prebuild-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use local Expo CLI
        run: npx expo --version

      - name: Install dependencies
        run: npm install

      - name: Run Expo Prebuild
        run: EXPO_USE_PRECOMPILED_MODULES=0 npx expo prebuild --clean

      - name: Upload iOS folder
        uses: actions/upload-artifact@v4
        with:
          name: ios-folder
          path: ios/
